"""Daily dealer-gamma profile — consumes the QuantitativeResearch option_research
OUTPUT files (not its code), so this stays decoupled from QR internals.

Per date it reads reports/option_atm_flip/<SYM>/<DATE>/{gex_curve.csv,candidate.json}
and returns the regime sign (net_gamma) + the zero-gamma flip level. Missing
profiles are batch-generated by shelling out to QR's CLI (ensure_profiles).

POINT-IN-TIME: a profile dated D reflects D's evening option chain (OI). To trade
D's session WITHOUT look-ahead, the feature layer uses the profile from the most
recent date STRICTLY BEFORE D — never D's own. This module just loads by date.
"""
from __future__ import annotations

import json
import os
import subprocess
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd

QR_REPO = Path(os.environ.get("QR_REPO", Path.home() / "Documents" / "GitHub" / "QuantitativeResearch"))
PROFILE_DIR = QR_REPO / "reports" / "option_atm_flip"
CHAIN_DIR = QR_REPO / "data" / "option"


@dataclass
class GammaProfile:
    date: str
    symbol: str
    net_gamma: float
    regime: int            # +1 net-positive dealer gamma, -1 net-negative
    flip: float | None     # zero-gamma spot in SYMBOL price units (None if none in range)
    spot_ref: float        # prior_close — anchor for basis-robust % mapping to ES


def flip_from_curve(spot, gex, near=None) -> float | None:
    """Zero-crossing(s) of gamma_exposure vs spot, linearly interpolated. Returns
    the crossing nearest ``near`` (default: the curve's mid spot), or None."""
    spot = np.asarray(spot, float); gex = np.asarray(gex, float)
    xs = []
    for i in range(1, len(gex)):
        y0, y1 = gex[i - 1], gex[i]
        if np.isfinite(y0) and np.isfinite(y1) and y0 != 0 and y1 != 0 and np.sign(y0) != np.sign(y1):
            x0, x1 = spot[i - 1], spot[i]
            xs.append(x0 - y0 * (x1 - x0) / (y1 - y0))
    if not xs:
        return None
    near = float(np.median(spot)) if near is None else float(near)
    return float(min(xs, key=lambda x: abs(x - near)))


def load_profile(date, symbol="SPY") -> GammaProfile | None:
    d = PROFILE_DIR / symbol / str(date)
    curve, cand = d / "gex_curve.csv", d / "candidate.json"
    if not curve.exists() or not cand.exists():
        return None
    c = json.loads(cand.read_text())
    g = pd.read_csv(curve)
    net = float(c["net_gamma"])
    spot_ref = float(c.get("prior_close") or c.get("snapshot_spot") or np.nan)
    flip = flip_from_curve(g["spot"], g["gamma_exposure"], near=spot_ref)
    return GammaProfile(str(date), symbol, net, 1 if net > 0 else -1, flip, spot_ref)


def available_dates(symbol="SPY") -> list[str]:
    d = PROFILE_DIR / symbol
    if not d.exists():
        return []
    return sorted(p.name for p in d.iterdir() if p.is_dir() and (p / "gex_curve.csv").exists())


def archived_chain_dates(symbol="SPY") -> list[str]:
    d = CHAIN_DIR / symbol
    if not d.exists():
        return []
    return sorted(p.name for p in d.iterdir() if (p / "chain.parquet").exists())


def ensure_profiles(dates, symbol="SPY", premarket=False) -> dict:
    """Batch-generate any missing profiles by calling QR's CLI. Returns {date: status}.

    QR isn't pip-installed in this env, so inject PYTHONPATH=<QR>/src; and route
    output to PROFILE_DIR (its CLI defaults to reports/option) with the atm_flip
    dealer-sign convention."""
    have = set(available_dates(symbol))
    cli = QR_REPO / "scripts" / "run_option_analysis.py"
    env = {**os.environ, "PYTHONPATH": str(QR_REPO / "src") + os.pathsep + os.environ.get("PYTHONPATH", "")}
    out_root = str(PROFILE_DIR.relative_to(QR_REPO))
    out: dict[str, str] = {}
    for dt in dates:
        if dt in have:
            out[dt] = "cached"; continue
        cmd = ["python", str(cli), "--symbol", symbol, "--date", str(dt),
               "--sign-convention", "atm_flip", "--output-root", out_root]
        if premarket:
            cmd.append("--premarket")
        r = subprocess.run(cmd, cwd=str(QR_REPO), capture_output=True, text=True, env=env)
        out[dt] = "ok" if r.returncode == 0 and load_profile(dt, symbol) else f"FAIL: {r.stderr.strip()[-160:]}"
    return out


def profile_frame(symbol="SPY") -> pd.DataFrame:
    """All available profiles as a date-indexed frame (regime, flip, net_gamma)."""
    rows = []
    for dt in available_dates(symbol):
        p = load_profile(dt, symbol)
        if p:
            rows.append(dict(date=p.date, net_gamma=p.net_gamma, regime=p.regime,
                             flip=p.flip, spot_ref=p.spot_ref))
    df = pd.DataFrame(rows)
    if not df.empty:
        df["date"] = pd.to_datetime(df["date"]); df = df.set_index("date").sort_index()
    return df
